development:
  adapter: postgresql
  encoding: unicode
  database: shopee_addon_development
  pool: 5
  username: jacob
  password: charlielee613

test:
  adapter: postgresql
  encoding: unicode
  database: shopee_addon_test
  pool: 5
  username: jacob
  password: charlielee613