# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: mysql2
  encoding: utf8mb4
  database: shopee_development
  host: localhost
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8mb4
  database: shopee_test
  host: localhost
  username: root
  password:

production:
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
